name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: rizuke/.github/.github/workflows/deploy-to-homelab.yaml@main
    permissions:
      id-token: write
    with:
      image-name: rizuke-dev
      container-name: rizuke
      container-network: main-tunnel
      deploy-secondary: true
    secrets:
      deploy-ssh-user: ${{ secrets.DEPLOY_SSH_USER }}
      deploy-node-primary: ${{ secrets.DEPLOY_NODE_PRIMARY }}
      deploy-node-secondary: ${{ secrets.DEPLOY_NODE_SECONDARY }}
      ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      ts-audience: ${{ secrets.TS_AUDIENCE }}