name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      id-token: write

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci

      - name: Deploy to raspi
        env:
          IMAGE: ghcr.io/${{ github.repository }}/rizuke-dev:latest
          RASPI_USER: ${{ secrets.RASPI_USER }}
          RASPI_TAILSCALE_HOSTNAME: ${{ secrets.RASPI_TAILSCALE_HOSTNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no "$RASPI_USER"@"$RASPI_TAILSCALE_HOSTNAME" "
            docker pull $IMAGE
            docker stop rizuke || true
            docker rm rizuke || true
            docker run -d \
              --name rizuke \
              --restart unless-stopped \
              -p 8000:80 \
              $IMAGE
          "